version: "3.7"

services:
  database:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment: 
      MYSQL_DATABASE: challenge
      MYSQL_ROOT_PASSWORD: root

  rabbitmq:
    image: rabbitmq:alpine
    restart: always
    ports: 
      - 5672:5672
      - 15672:15672
    environment: 
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
